### ISSUE TITLE
sexe:  M/F

### ISSUE THREAD

**Issue by Balestro** [jehon/cryptomedic#48]
dans les report il y a des ?? dans la colonne M/F

**Comment by jehon** [comment]
Oui, cela signifie: sexe inconnu

C'est utilisé à l'encodage en france, lorsque le sexe n'est pas lisible ou n'est pas écrit sur la fiche.

Est-ce ok pour toi?

**Comment by Balestro** [comment]
Je comprends ce que tu écris mais chez moi toute la colonne "sexe" est avec  "??"
