### ISSUE TITLE
Changer le summary de la picture

### ISSUE THREAD

**Issue by Balestro** [jehon/cryptomedic#49]
J'ai testé le Add Picture. Ça marche bien. 
Sur mon MAC, une photo de 1,7Mo met 30" à être transférée., ce qui peut faire 10 fois plus à Chakaria.
Il faut donc, comme tu l'as écrit, que localement la photo soit redimentionnée. En attendant cette fonction, ce serait bien de mettre un avertissement qui rappelle le poids max d'une photo et qui refuse la photo trop lourde.

Petit détails:
dans les commentaires, le retour à la ligne utilisé en mode "edit" ne se retrouve pas après le "save".

Lors du "add picture" après le premier "save"  il manque des infos à l'écran. Ces infos réapparaisent lorsque que lon clic dans la liste de gauche "bill", "picture" etc...

Dans le summary on ne voit pas la photo en miniature ni les informations importantes.
Il faudrait peut être que dans le "summary" apparaisse la date de la photo et non le date à laquelle elle a été entrée dans la base.

A part ça c'est tout bon.

![photo 1](https://cloud.githubusercontent.com/assets/9754736/5602744/0a0b563a-9363-11e4-9227-86a2b36d2617.jpg)

**Comment by jehon** [comment]
Donc, il faut surtout changer le summary de la picture :-)

- pour le passage à la ligne, c'est fait
- pour l'upload, voir autre bug

**Comment by Balestro** [comment]
Je crois qu'il faudrait que l'on voie avec Thierry ce qu'il faudrait trouver dans le "summary" du patient. Donc, si pour le moment, l'entrée des photos se fait restons en là en attendant plus de précisions après discussion avec Thierry sur le "summary".
