### ISSUE TITLE
SL dans les "report" différent du SL dans la "Bill"

### ISSUE THREAD

**Issue by Balestro** [jehon/cryptomedic#51]
La valeur du SL affichée dans les "report" ne correspond pas toujours à celle qui est calculée dans la "bill"...

![sl](https://cloud.githubusercontent.com/assets/9754736/5671656/f8ae9124-9789-11e4-8d0e-d312c763bb1f.png)
![sl1](https://cloud.githubusercontent.com/assets/9754736/5671658/ff7f51c8-9789-11e4-8689-655179efa052.png)

**Comment by jehon** [comment]
Le SL affiché dans le rapport est le SL qui est encodé manuellement dans la
bill, pas le SL calculé.

Est-ce que c'est le comportement voulu?
Est-ce que alors le problème est alors toujours d'actualité?

**Comment by Balestro** [comment]
Le SL affiché dans le "report" pour cet exemple 4 n'est ni le SL calculé 3, ni le SL encodé manuellement 2?

**Comment by jehon** [comment]
J'y regarde...

2015-01-11 22:26 GMT+01:00 Balestro <notifications@github.com>:

**Comment by jehon** [comment]
Est-ce que tu peux voir si le problème est résolu ou pas dans la dernière version que je viens d'installer?

Merci

**Comment by Balestro** [comment]
Pour moi, c'est OK
Merci
