### ISSUE TITLE
initialisations des items "report"

### ISSUE THREAD

**Issue by Balestro** [jehon/cryptomedic#54]
Il faudrait généraliser l'initialisation du  "Who, Where, When" aux valeurs de la précédente consultation de ces "report".

**Comment by jehon** [comment]
Bonjour Freddy
C'est désormais le cas. Toutefois, ces valeurs sont perdues si on ferme le browser. Penses-tu qu'il serait intéressant de garder ces valeurs d'une fois à l'autre?

Bàt,
Jean

**Comment by Balestro** [comment]
Salut Jean
A priori, je dirais qu'il faut conserver ces valeurs durant la journée, afin de pouvoir revenir sur une entrée de données de manière simple même si on a fermé son ordinateur dans la journée.
Après le délai de la journée, l'initialisation actuelle semble correcte. 
On peut se poser la question sur le MR et le MSR: est ce que l'on initialise au mois précédent ou au mois courant?
Bonne journée
Freddy

**Comment by jehon** [comment]
Re-

C'est difficile d'initialiser pour une journée... Le plus simple, c'est
soit pour la session (jusqu'à la fermeture), soit pour longtemps (et
résistant à la fermeture). Le reste est un peu plus complexe.

Pour les rapports, je prends le mois précédent (donc le dernier mois
complet).

**Comment by Balestro** [comment]
L'initialisation pour une session est un bon choix.

**Comment by jehon** [comment]
Ok
C'est le comportement en cours, je ne change donc rien :-)
