### ISSUE TITLE
Chronologie dans Monthly Activity Report

### ISSUE THREAD

**Issue by Balestro** [jehon/cryptomedic#55]
Pourquoi la liste des patients dans le MAR n'est pas chronologique en fonction de la date de visite?

**Comment by jehon** [comment]
Parce que personne ne l'a demandé :-)
Je vais te faire ça
Jean

**Comment by Balestro** [comment]
Ça marche pas???

**Comment by jehon** [comment]
c'est pas encore installé. Lorsqu'un bug est fermé, il faut attendre
d'avoir l'avis disant que la version est installée avant d'avoir le nouveau
résultat :-)

2015-01-28 15:12 GMT+01:00 Balestro <notifications@github.com>:

**Comment by Balestro** [comment]
OK, je saurai pour une prochaine fois.

Le 28 janv. 2015 à 15:28, Jehon a écrit :

c'est pas encore installé. Lorsqu'un bug est fermé, il faut attendre 
d'avoir l'avis disant que la version est installée avant d'avoir le nouveau 
résultat :-) 

2015-01-28 15:12 GMT+01:00 Balestro <notifications@github.com>:

**Comment by jehon** [comment]
Voilà, c'est installé
