### ISSUE TITLE
summary

### ISSUE THREAD

**Issue by biboundette** [jehon/cryptomedic#56]
coucou Jean
Lorsque je fais un résumé du patient. Dans la rubrique "surgery" il apparaît le message suivant et je ne vois pas l'erreur :Read: key is not in the database: 'Surgery.Operation'.
tu peux le constater sur le patient : "2008-117" Sala Uddin
Merci de me dire ce qu'il faut renseigner.
a bientôt

dominique

**Comment by jehon** [comment]
Bonjour

Comment faites-vous pour arriver jusque là?
Le plus simple serait de me donner l'adresse de la page, savez-vous comment
faire?

Jean

**Comment by biboundette** [comment]
http://cryptomedic.org/cryptomedic/app/#/folder/80117/patient

voilà je pense que c'est ça

 

 

-----E-mail d'origine-----
De : Jehon <notifications@github.com>
A: jehon/cryptomedic <cryptomedic@noreply.github.com>
Cc: biboundette <domiepuech@aol.com>
Envoyé le : Ma, 10 Fév 2015 20:11
Sujet : Re: [cryptomedic] summary (#56)


Bonjour

Comment faites-vous pour arriver jusque là?
Le plus simple serait de me donner l'adresse de la page, savez-vous comment
faire?

Jean

**Comment by jehon** [comment]
Ok merci

J'ai trouvé: il n'y a rien à faire, c'est un champ qui a disparu. Je dois
adapter la page "résumé", et je le fais très prochainement, dès que j'ai
fini un autre truc.

Est-ce gênant?

Bonne soirée
Jaen

**Comment by biboundette** [comment]
Non bien sûr
Faudra-t-il alors que je reprenne tous les dossiers ?

 

-----E-mail d'origine-----
De : Jehon <notifications@github.com>
A: jehon/cryptomedic <cryptomedic@noreply.github.com>
Cc: biboundette <domiepuech@aol.com>
Envoyé le : Ma, 10 Fév 2015 21:05
Sujet : Re: [cryptomedic] summary (#56)


Ok merci

J'ai trouvé: il n'y a rien à faire, c'est un champ qui a disparu. Je dois
adapter la page "résumé", et je le fais très prochainement, dès que j'ai
fini un autre truc.

Est-ce gênant?

Bonne soirée
Jaen

**Comment by jehon** [comment]
Rien, dès que mon fix sera là, tous les dossiers seront bien affichés...

**Comment by jehon** [comment]
C'est normalement fixé. Peux-tu vérifier?
