### ISSUE TITLE
SEL

### ISSUE THREAD

**Issue by Balestro** [jehon/cryptomedic#58]
Bonjour Jean
Après un long silence ( preuve que tout marche bien ) me voilà de retour...
Pour faire suite à  #53 "réflexion autoiur du SEL" et après discussion avec Thierry, nous pensons que le seul SEL qui doit aparaître est le SEL calculé à partir des données fournies.
Donc dans la "case" summary il faut recopier le SEL calculé dans la "case" Social Data
Bonne soirée
Freddy

**Comment by jehon** [comment]
Est-ce que le SEL recopié dans summary doit être modifiable?

Jean

**Comment by Balestro** [comment]
C'est une bonne question; j'ai beau me creuser les méninges, je ne vois pas dans quel cas on aurait à modifier le SEL après qu'il ait été calculé.
Donc faisons en sorte qu'il ne soit pas modifiable.

**Comment by jehon** [comment]
C'est fait
