### ISSUE TITLE
la fonction "view" ne marche pas

### ISSUE THREAD

**Issue by Balestro** [jehon/cryptomedic#64]
Bonjour
cela fait quelques jours que "VIEW" ne marche pas.
C'est une fonction très utile
Bonne journée
Freddy

**Comment by jehon** [comment]
Bonjour Freddy

Où trouves-tu ce "VIEW" ?

PS: en effet, tout doit marcher :-)

Merci
Jean

2015-06-16 8:31 GMT+02:00 Balestro <notifications@github.com>:

**Comment by Balestro** [comment]
![view](https://cloud.githubusercontent.com/assets/9754736/8179742/f563a606-1418-11e5-9053-ef60b7eb46fa.png)
